name: Agent Deployment

on:
  push:
    branches:
      - main

jobs:
  data-collection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Prepare env variables
        run: cp env.example .env
        working-directory: packages/env

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma types
        run: pnpm generate
        working-directory: packages/prisma

      - name: Build
        run: pnpm build --filter=data-collection-agent

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        working-directory: ./apps/agents/data-collection
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  content-generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Prepare env variables
        run: cp env.example .env
        working-directory: packages/env

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma types
        run: pnpm generate
        working-directory: packages/prisma

      - name: Build
        run: pnpm build --filter=content-generation-agent

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        working-directory: ./apps/agents/content-generation
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Prepare env variables
        run: cp env.example .env
        working-directory: packages/env

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma types
        run: pnpm generate
        working-directory: packages/prisma

      - name: Build
        run: pnpm build --filter=delivery-agent

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        working-directory: ./apps/agents/delivery
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
