name: App Deployment

on:
  push:
    branches:
      - main

jobs:
  agent-auth-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Prepare env variables
        run: cp env.example .env
        working-directory: packages/env

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma types
        run: pnpm generate
        working-directory: packages/prisma

      - name: Build
        run: pnpm build --filter=agent-auth-api

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        working-directory: ./apps/agent-auth-api
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  agent-data-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Prepare env variables
        run: cp env.example .env
        working-directory: packages/env

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma types
        run: pnpm generate
        working-directory: packages/prisma

      - name: Build
        run: pnpm build --filter=agent-data-api

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        working-directory: ./apps/agent-data-api
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  agent-registry-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Prepare env variables
        run: cp env.example .env
        working-directory: packages/env

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma types
        run: pnpm generate
        working-directory: packages/prisma

      - name: Build
        run: pnpm build --filter=agent-registry-api

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        working-directory: ./apps/agent-registry-api
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Prepare env variables
        run: cp env.example .env
        working-directory: packages/env

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma types
        run: pnpm generate
        working-directory: packages/prisma

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        run: flyctl deploy --remote-only -c apps/dashboard/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  hermes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Prepare env variables
        run: cp env.example .env
        working-directory: packages/env

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma types
        run: pnpm generate
        working-directory: packages/prisma

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        run: flyctl deploy --remote-only -c apps/hermes/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
